var PROJECTION_TOP = 1;
var PROJECTION_ISO = 2;
var PROJECTION_SIDE = 3;

var MIRRORLINE_DEFAULT = -1;

var MIRRORMODE_RANDOM = -1;
var MIRRORMODE_POINT = 0;
var MIRRORMODE_AXIS = 1;

var MIN_SEQUENCE_LENGTH = 40;
var MAX_SEED_VALUE = 123321;
